import pygame
from pygame.event import Event
from resources.assets import Assets
from screens.screens import Screen
from utils.text import BOOT_TEXT
from utils.events import SELECT
from utils.constants import (
    PIPBOY_GREEN,
    LEFT_EDGE,
    TOP_EDGE,
    TYPEWRITER_CHARACTER_DELAY,
    TYPEWRITER_CURSOR_BLINK_DELAY,
    TYPEWRITER_CURSOR_DURATION,
    TYPEWRITER_CURSOR_SYMBOL,
)
"""Typewriter boot screen for PipBoy initialization sequence.
"""

class TypewriterTextScreen(Screen):
    def __init__(self, assets: Assets) -> None:
        """ Initializes constants responsible for typewriter effect

        Args:
            assets (Assets): assets passed through by PipBoy
        """
        super().__init__(assets)
        self.boot_text: list[str] = BOOT_TEXT

        self.visible_lines: list[str] = [""] * len(self.boot_text)
        self.current_line: int = 0
        self.current_char_index: int = 0
        self.type_timer: float = 0.0
        self.type_speed: float = TYPEWRITER_CHARACTER_DELAY
        self.typewriter_complete: bool = False

        self.cursor_visible: bool = True
        self.cursor_timer: float = 0.0
        self.cursor_blink_speed: float = TYPEWRITER_CURSOR_BLINK_DELAY
        self.cursor_symbol: str = TYPEWRITER_CURSOR_SYMBOL
        self.cursor_duration: float = TYPEWRITER_CURSOR_DURATION
        self.cursor_elapsed: float = 0.0

        self.text_surface: pygame.Surface = self.generate_text_surface()
        self.complete: bool = False

    def event_handler(self, event: Event) -> None:
        if event.type == SELECT:
            self.complete = True

    def update(self, dt: float) -> None:
        """ Checks if screen animation is complete. If not complete, animates bootup 
        text line by line and creates a blinking cursor once animation is complete.

        Args:
            dt (float): time between frames
        """
        if self.complete:
            return

        self.type_timer += dt
        while self.type_timer >= self.type_speed and not self.typewriter_complete:
            self.type_timer -= self.type_speed

            # Handles when text is fully rendered
            if self.current_line >= len(self.boot_text):
                self.typewriter_complete = True
                self.current_line = len(self.boot_text) - 1
                break

            full_line: str = self.boot_text[self.current_line]

            # Handles situation when lines are blank
            if len(full_line) == 0:
                self.visible_lines[self.current_line] = ""
                self.current_line += 1
                self.current_char_index = 0
                continue
            
            # Reveals the next character
            self.current_char_index += 1
            self.visible_lines[self.current_line] = full_line[: self.current_char_index]

            # Moves onto next line if line is complete
            if self.current_char_index >= len(full_line):
                self.current_line += 1
                self.current_char_index = 0

        # Updates cursor elapsed time
        if self.typewriter_complete:
            self.cursor_timer += dt
            self.cursor_elapsed += dt

        # Updates screen state if cursor duration is complete
        if self.cursor_elapsed >= self.cursor_duration:
            self.complete = True
            return

        # Toggles cursos visibility
        while self.cursor_timer >= self.cursor_blink_speed and self.typewriter_complete:
            self.cursor_timer -= self.cursor_blink_speed
            if self.cursor_visible:
                self.cursor_visible = False
            else:
                self.cursor_visible = True

        self.text_surface = self.generate_text_surface()

    def draw(self, screen: pygame.Surface) -> None:
        """ draws the screen to the display surface

        Args:
            screen (pygame.Surface): display surface generated by screen
        """
        screen.blit(self.text_surface, (LEFT_EDGE, TOP_EDGE))

    def generate_text_surface(self) -> pygame.Surface:
        """ generates pygame surface containing currently visible text and appends cursor to end of line if visible

        Returns:
            pygame.Surface: returns the text surface for future render
        """
        line_surfaces: list[pygame.Surface] = []

        # Renders each visible line with optional cursor
        for index, text in enumerate(self.visible_lines):
            if index == self.current_line and self.cursor_visible:
                line_surfaces.append(
                    self.assets.fonts["small"].render(
                        text + self.cursor_symbol, True, PIPBOY_GREEN
                    )
                )
            else:
                line_surfaces.append(
                    self.assets.fonts["small"].render(text, True, PIPBOY_GREEN)
                )
        
        # Compute layout dimensions
        line_size: int = self.assets.fonts["small"].get_linesize()
        width: int = max(1, max(surf.get_width() for surf in line_surfaces))
        height: int = len(line_surfaces) * line_size

        # Create surface
        surface = pygame.Surface((width, height), pygame.SRCALPHA)
        surface = surface.convert_alpha()

        # Blit lines onto surface
        for index, surf in enumerate(line_surfaces):
            surface.blit(surf, (0, index * line_size))

        return surface
